
[functions.send-signal-to-telegram]
enabled = true
verify_jwt = false
import_map = "./functions/send-signal-to-telegram/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-signal-to-telegram/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-signal-to-telegram/*.html" ]

[functions.send-new-launch-to-telegram]
enabled = true
verify_jwt = false
import_map = "./functions/send-new-launch-to-telegram/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-new-launch-to-telegram/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-new-launch-to-telegram/*.html" ]
